export default {
    INCREASE_SELECTOR_VALUE: 'INCREASE_SELECTOR_VALUE',
    DECREASE_SELECTOR_VALUE: 'DECREASE_SELECTOR_VALUE',
    SWITCH_CLIMATE: 'SWITCH_CLIMATE',
    SWITCH_WHEELS: 'SWITCH_WHEELS'

}